adjective=raw_input('please enter an adjective:')
noun=raw_input('please enter a noun:')
verb=raw_input('please enter a verb ending in -ed:')
animal=raw_input('please enter an animal:')
print('Your MadLib:')
print('The'+" "+adjective+" "+noun+" "+verb+" "+'over the lazy brown'+" "+animal+'.')